version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: listings_db
      POSTGRES_USER: listings_user
      POSTGRES_PASSWORD: listings_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=listings_db
      - POSTGRES_USER=listings_user
      - POSTGRES_PASSWORD=listings_pass
      - POSTGRES_HOST=db

volumes:
  postgres_data:
